# Generated by Django 3.0.11 on 2020-12-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_sitting_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='answers_at_end',
        ),
    ]
