# Generated by Django 3.0.11 on 2020-12-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_quiz_answers_at_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcquestion',
            name='allow_multiple_answers',
            field=models.BooleanField(default=False, help_text='If true, the user can select several answers', verbose_name='Allow several answers'),
        ),
    ]
