# Generated by Django 3.0.11 on 2020-12-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_mcquestion_allow_multiple_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(help_text='Enter the question text that you want displayed', max_length=1000, verbose_name='Question'),
        ),
    ]
