# Generated by Django 3.0.11 on 2020-12-14 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0009_auto_20201213_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Order of the question in the sitting')),
                ('answer', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='User answer')),
                ('is_correct', models.BooleanField(default=None, null=True, verbose_name='Is correct')),
                ('question', models.ForeignKey(help_text='question the user answered to', on_delete=django.db.models.deletion.CASCADE, to='quiz.Question', verbose_name='Question')),
                ('sitting', models.ForeignKey(help_text='Sitting this answer is linked to', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.Sitting', verbose_name='Sitting')),
                ('user', models.ForeignKey(help_text='User that generated this answer', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
