# Generated by Django 3.0.11 on 2020-12-16 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_useranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitting',
            name='incorrect_questions',
        ),
        migrations.RemoveField(
            model_name='sitting',
            name='question_list',
        ),
    ]
