# Generated by Django 3.0.11 on 2020-12-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20201216_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcquestion',
            name='answer_order',
            field=models.CharField(blank=True, choices=[('content', 'Content'), ('random', 'Random'), ('none', 'None')], default='random', help_text='The order in which multichoice answer options are displayed to the user', max_length=30, null=True, verbose_name='Answer Order'),
        ),
    ]
