# Generated by Django 3.0.11 on 2021-01-03 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20201216_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.Question')),
                ('answer', models.CharField(help_text='Answer to the question', max_length=50, verbose_name='Answer')),
                ('answer_type', models.CharField(choices=[('number', 'Number'), ('string', 'String')], default='number', help_text='Type of the expected answer', max_length=8, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Open Question',
                'verbose_name_plural': 'Open Questions',
                'ordering': ['category'],
            },
            bases=('quiz.question',),
        ),
    ]
