# Generated by Django 3.0.11 on 2021-01-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20210111_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='sub_category',
        ),
    ]
