# Generated by Django 3.0.11 on 2021-01-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_remove_question_sub_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openquestion',
            options={'verbose_name': 'Open Question', 'verbose_name_plural': 'Open Questions'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['content'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='tfquestion',
            options={'verbose_name': 'True/False Question', 'verbose_name_plural': 'True/False Questions'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='questions', to='quiz.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='figure',
            field=models.ImageField(blank=True, null=True, upload_to='questions', verbose_name='Figure'),
        ),
    ]
