# Generated by Django 3.0.11 on 2021-01-20 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20210120_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='figure',
        ),
    ]
