# Generated by Django 3.0.11 on 2021-01-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_remove_question_figure'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('topic', 'Topic'), ('monthly', 'Monthly')], default='general', max_length=10, verbose_name='Type'),
        ),
    ]
